accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

movieblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from posts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('<int:post_id>/comments/add/', views.add_comment, name='comment_add'),
    path('<int:post_id>/comments/<int:comment_id>/remove', views.remove_comment, name='comment_remove'),
]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('<int:pk>/', views.ProfileView.as_view(), name='profile_details'),
    path('<int:pk>/update/', views.update_profile, name='profile_update'),
    path('bookmarks/', views.FavouritePostListView.as_view(), name='bookmarks'),
    path('bookmarks/<int:post_id>/add/', views.add_to_bookmarks, name='bookmark_add'),
    path('bookmarks/<int:post_id>/remove/', views.remove_from_bookmarks, name='bookmark_remove'),
]

profiles/models.py
from django.contrib.auth.models import User
from django.db import models

from movieblog.services import compress_image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='movieblog/profiles/images', blank=True, null=True)
    posts = models.ManyToManyField('posts.Post')
    is_subscribed = models.BooleanField(default=True, blank=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.image:
            self.image = compress_image(image=self.image, max_res=640)
        super().save(*args, **kwargs)

profiles/forms.py
from django import forms


class ProfileForm(forms.Form):
    image = forms.ImageField(required=False, widget=forms.FileInput(attrs={
        'class': 'user__image-input'
    }))
    username = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={
        'class': 'register__window-input',
        'placeholder': 'Имя пользователя'
    }))
    is_subscribed = forms.BooleanField(required=None)

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView

from posts.models import Post
from profiles.forms import ProfileForm


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = 'user'
    template_name = 'profiles/profile_details.html'

    def get(self, request, *args, **kwargs):
        user_id = self.kwargs.get('pk')
        if self.request.user.id != user_id:
            return HttpResponseForbidden()
        return super().get(request, *args, **kwargs)


class FavouritePostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'profiles/profile_post_list.html'

    def get_queryset(self):
        user = self.request.user
        posts = Post.objects.filter(profile__user_id=user.id).select_related('category')
        return posts


@login_required
def add_to_bookmarks(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    next_url = request.POST.get('next')
    if post and user:
        user.profile.posts.add(post)
        user.save()
        return redirect(next_url)
    else:
        return redirect('home')


@login_required
def remove_from_bookmarks(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    user = request.user
    next_url = request.POST.get('next')
    if post and user:
        user.profile.posts.remove(post)
        user.save()
        return redirect(next_url)
    else:
        return redirect('home')


@login_required
def update_profile(request, pk):
    user = request.user
    if user.pk != pk:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data
            user.username = data['username']
            if data['image']:
                user.profile.image = request.FILES['image']
            user.profile.is_subscribed = data['is_subscribed']
            user.save()
            return redirect(reverse('profiles:profile_details', kwargs={'pk': user.pk}))
        else:
            return render(request, 'profiles/profile_update.html', {'form': form})
    else:
        form = ProfileForm(initial={
            'username': user.username,
            'image': user.profile.image,
            'is_subscribed': user.profile.is_subscribed}
        )
        return render(request, 'profiles/profile_update.html', {'form': form})

templates/movieblog/profiles/profile_details.html
{% extends 'movieblog/base_profile.html' %}
{% load static %}

{% block title %}
    Профиль
{% endblock %}

{% block content %}
    <section class="container account__control-wrapper">
        <div class="user__portfolio">
            {% if user.profile.image %}
                <img src="{{ user.profile.image.url }}" alt="User image">
            {% else %}
                <img src="{% static 'images/default_user_img.png' %}" alt="Default user image">
            {% endif %}
            <div class="user__portfolio-details">
                <span>Имя пользователя</span>
                <h1>{{ user.username|truncatechars:20 }}</h1>
                <span>Email</span>
                <h2>{{ user.email|truncatechars:20 }}</h2>
            </div>
            <img class="user__portfolio-icons" src="{% static 'images/003-spotlight.png' %}" alt="spotlight icon">
        </div>
        <div class="user__buttons">
            <a href="{% url 'profiles:profile_update' user.id %}">Редактировать профиль</a>
            <a href="{% url 'accounts:password_change' %}">Сменить пароль</a>
        </div>
    </section>
{% endblock %}

templates/movieblog/profiles/profile_post_list.html
{% extends 'movieblog/base_profile.html' %}
{% load static %}


{% block title %}
    Избранные новости
{% endblock %}

{% block content %}
    <section class="container favorite-news">
        <h1>Избранные новости</h1>
        <div class="news__wrapper">
            {% for post in posts %}
                <div class="news__item">
                    {% if post.image %}
                        <img class="news__item-img" src="{{ post.image.url }}" alt="Post image">
                    {% else %}
                        <img class="news__item-img" src="{% static 'images/default_post_img.jpg' %}"
                             alt="Default post image">
                    {% endif %}
                    <form action="{% url 'profiles:bookmark_remove' post.id %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.get_full_path }}">
                        <button class="fav-icon active">
                            <svg height="511pt" viewBox="0 -10 511.98645 511" width="511pt"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="m499.574219 188.503906c-3.199219-9.921875-11.988281-16.9375-22.398438-17.898437l-141.355469-12.84375-55.894531-130.835938c-4.117187-9.578125-13.503906-15.765625-23.933593-15.765625-10.433594 0-19.820313 6.207032-23.9375 15.808594l-55.890626 130.816406-141.378906 12.839844c-10.386718.941406-19.175781 7.957031-22.378906 17.878906-3.21875 9.921875-.234375 20.777344 7.617188 27.648438l106.859374 93.695312-31.511718 138.773438c-2.300782 10.199218 1.664062 20.734375 10.136718 26.878906 4.519532 3.328125 9.875 4.992188 15.230469 4.992188 4.628907 0 9.238281-1.234376 13.355469-3.710938l121.898438-72.894531 121.875 72.875c8.917968 5.351562 20.160156 4.882812 28.609374-1.238281 8.46875-6.144532 12.4375-16.683594 10.132813-26.882813l-31.507813-138.769531 106.859376-93.699219c7.847656-6.867187 10.835937-17.726563 7.613281-27.667969zm0 0"
                                      fill="#ffc107"/>
                                <path d="m114.617188 491.136719c-5.632813 0-11.203126-1.746094-15.957032-5.183594-8.855468-6.398437-12.992187-17.429687-10.582031-28.09375l32.9375-145.066406-111.703125-97.964844c-8.210938-7.1875-11.347656-18.515625-7.976562-28.90625 3.371093-10.367187 12.542968-17.726563 23.402343-18.730469l147.820313-13.417968 58.410156-136.746094c4.308594-10.046875 14.121094-16.535156 25.023438-16.535156 10.902343 0 20.714843 6.488281 25.023437 16.511718l58.410156 136.769532 147.796875 13.417968c10.882813.980469 20.054688 8.34375 23.425782 18.710938 3.371093 10.386718.253906 21.738281-7.980469 28.90625l-111.679688 97.941406 32.9375 145.066406c2.414063 10.667969-1.726562 21.695313-10.578125 28.09375-8.8125 6.378906-20.566406 6.914063-29.890625 1.324219l-127.464843-76.160156-127.445313 76.203125c-4.308594 2.582031-9.109375 3.859375-13.929687 3.859375zm141.375-112.871094c4.84375 0 9.640624 1.300781 13.953124 3.859375l120.277344 71.9375-31.085937-136.941406c-2.21875-9.769532 1.089843-19.925782 8.621093-26.515625l105.472657-92.523438-139.542969-12.671875c-10.003906-.894531-18.667969-7.1875-22.59375-16.46875l-55.101562-129.046875-55.148438 129.066407c-3.902344 9.238281-12.5625 15.53125-22.589844 16.429687l-139.519531 12.671875 105.46875 92.519531c7.554687 6.59375 10.839844 16.769531 8.621094 26.539063l-31.082031 136.941406 120.277343-71.9375c4.328125-2.558594 9.128907-3.859375 13.972657-3.859375zm-84.585938-221.824219v.019532zm169.152344-.066406v.023438s0 0 0-.023438zm0 0"/>
                            </svg>
                        </button>
                    </form>
                    <a href="{% url 'posts:post_details' post.id %}" class="news__item-details">Подробнее</a>
                    <div class="news__item-header">
                        <span class="news__item-category">{{ post.category.name }}</span>
                        <p class="news__item-title">{{ post.title|truncatechars:80 }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

templates/movieblog/profiles/profile_update.html
{% extends 'movieblog/base_account.html' %}
{% load static %}

{% block title %}
    Редактирование профиля
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'js/fileInput.js' %}"></script>
{% endblock %}

{% block content %}
    <section class="container edit__account-window">
        <form action="" class="register__window-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="toggle__mode">
                <input type="checkbox" class="toggle-mode__checkbox" id="toggle-mode__checkbox">
                <label class="toggle-mode__label" for="toggle-mode__checkbox">
                    <i class="fas fa-moon"></i>
                    <i class="fas fa-sun"></i>
                    <span class="toggle-mode__ball"></span>
                </label>
            </div>
            <h1>Редактирование пользователя</h1>
            <div class="register__window-form-content">
                <label for="{{ form.image.id_for_label }}">
                    {% if user.profile.image %}
                        <img src="{{ user.profile.image.url }}" class="user__image" alt="User image">
                    {% else %}
                        <img src="{% static 'images/default_user_img.png' %}" class="user__image"
                             alt="Default user image">
                    {% endif %}
                </label>
                {{ form.image }}
                {{ form.username }}
                <div class="custom-form-group-checkbox">
                    <label class="checkbox-label" for="{{ form.is_subscribed.id_for_label }}">Уведомлять о
                        новостях:</label>
                    {{ form.is_subscribed }}
                </div>
                <div class="edit__account-buttons">
                    <button class="register__window-button" type="submit">Сохранить</button>
                    <a href="{% url 'profiles:profile_details' user.id %}">Вернуться</a>
                </div>
            </div>
            <img class="register__window-form-img movie-script" src="{% static 'images/044-script.png' %}"
                 alt="chair icon">
            <img class="register__window-form-img director-chair" src="{% static 'images/032-director-chair.png' %}"
                 alt="chair icon">
        </form>
    </section>
{% endblock %}