accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

movieblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from posts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('<int:post_id>/comments/add/', views.add_comment, name='comment_add'),
    path('<int:post_id>/comments/<int:comment_id>/remove', views.remove_comment, name='comment_remove'),
]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('<int:pk>/', views.ProfileView.as_view(), name='profile_details'),
    path('<int:pk>/update/', views.update_profile, name='profile_update'),
    path('bookmarks/', views.FavouritePostListView.as_view(), name='bookmarks'),
    path('bookmarks/<int:post_id>/add/', views.add_to_bookmarks, name='bookmark_add'),
    path('bookmarks/<int:post_id>/remove/', views.remove_from_bookmarks, name='bookmark_remove'),
]

templates/movieblog/base_account.html
{% extends 'movieblog/base.html' %}
{% load static %}

{% block content %}
{% endblock %}

templates/movieblog/navbar.html
{% load static %}

<nav id="navbar">
    <div class="navbar__container">
        <a href="{% url 'home' %}" class="navbar__logo">
            <img src="{% static 'images/movieblog.png' %}" alt="Navbar logo">
            <span>MovieBlog</span>
        </a>
        <div class="toggle__mode">
            <input type="checkbox" class="toggle-mode__checkbox" id="toggle-mode__checkbox">
            <label class="toggle-mode__label" for="toggle-mode__checkbox">
                <i class="fas fa-moon"></i>
                <i class="fas fa-sun"></i>
                <span class="toggle-mode__ball"></span>
            </label>
        </div>
    </div>
    <div class="navbar__menu">
        <ul>
            <li>
                <a href="{% url 'posts:post_list' %}">Новости</a>
            </li>
            <li>
                <a>
                    Жанры
                    <svg class="navbar__menu-arrow" xmlns="http://www.w3.org/2000/svg"
                         width="451.847px" height="451.847px" viewBox="0 0 451.847 451.847"
                         xml:space="preserve">
                        <g>
                            <path d="M225.923,354.706c-8.098,0-16.195-3.092-22.369-9.263L9.27,151.157c-12.359-12.359-12.359-32.397,0-44.751
                                            c12.354-12.354,32.388-12.354,44.748,0l171.905,171.915l171.906-171.909c12.359-12.354,32.391-12.354,44.744,0
                                            c12.365,12.354,12.365,32.392,0,44.751L248.292,345.449C242.115,351.621,234.018,354.706,225.923,354.706z"/>
                        </g>
                    </svg>
                </a>
                <ul class="dropdown">
                    {% for category in categories %}
                        <li>
                            <a href="{% url 'posts:post_list' %}?category={{ category.id }}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'profiles:profile_details' user.id %}">
                        Личный кабинет
                        <svg class="navbar__menu-arrow" xmlns="http://www.w3.org/2000/svg"
                             width="451.847px" height="451.847px" viewBox="0 0 451.847 451.847"
                             xml:space="preserve">
                            <g>
                                <path d="M225.923,354.706c-8.098,0-16.195-3.092-22.369-9.263L9.27,151.157c-12.359-12.359-12.359-32.397,0-44.751
                                                                c12.354-12.354,32.388-12.354,44.748,0l171.905,171.915l171.906-171.909c12.359-12.354,32.391-12.354,44.744,0
                                                                c12.365,12.354,12.365,32.392,0,44.751L248.292,345.449C242.115,351.621,234.018,354.706,225.923,354.706z"/>
                            </g>
                        </svg>
                    </a>
                    <ul class="dropdown">
                        <li>
                            <a href="{% url 'profiles:profile_details' user.id %}">Мой профиль</a>
                        </li>
                        <li>
                            <a href="{% url 'profiles:bookmarks' %}">Избранные новости</a>
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="navbar__buttons">
        {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}?next={{ request.path }}" method="post">
                {% csrf_token %}
                <button type="submit" class="navbar__button logout">Выйти</button>
            </form>
        {% else %}
            <a href="{% url 'accounts:register' %}" class="navbar__button register">Зарегистрироваться</a>
            <a href="{% url 'accounts:login' %}?next={{ request.path }}" class="navbar__button login">Войти</a>
        {% endif %}
    </div>
    <div class="navbar__burger">
        <span></span>
    </div>
</nav>