movieblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from posts.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('posts/', include('posts.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_details'),
    path('<int:post_id>/comments/add/', views.add_comment, name='comment_add'),
    path('<int:post_id>/comments/<int:comment_id>/remove', views.remove_comment, name='comment_remove'),
]

profiles/urls.py
from django.urls import path

from profiles import views

app_name = 'profiles'

urlpatterns = [
    path('<int:pk>/', views.ProfileView.as_view(), name='profile_details'),
    path('<int:pk>/update/', views.update_profile, name='profile_update'),
    path('bookmarks/', views.FavouritePostListView.as_view(), name='bookmarks'),
    path('bookmarks/<int:post_id>/add/', views.add_to_bookmarks, name='bookmark_add'),
    path('bookmarks/<int:post_id>/remove/', views.remove_from_bookmarks, name='bookmark_remove'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse
from django.utils import timezone
from ckeditor import fields

from profiles.models import Profile
from movieblog.services import compress_image


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = fields.RichTextField()
    pub_date = models.DateTimeField(default=timezone.now, editable=False)
    mod_date = models.DateTimeField(blank=True, null=True, editable=False)
    image = models.ImageField(upload_to='movieblog/posts/images/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post_details', kwargs={'pk': str(self.pk)})

    def save(self, *args, **kwargs):
        if self.image:
            self.image = compress_image(self.image)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('-pub_date',)


class Comment(models.Model):
    content = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now, editable=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.post.title}'

    class Meta:
        ordering = ('pub_date',)

posts/forms.py
from django import forms

from posts.models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'post__comments-input',
                'placeholder': 'Оставить комментарий'
            })
        }

posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView

from .models import Post, Comment
from .forms import CommentForm


class HomeView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'posts/index.html'

    def get_queryset(self):
        posts = Post.objects.select_related('category')[:6]
        return posts

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        return context


class PostListView(HomeView):
    paginate_by = 12
    template_name = 'posts/post_list.html'
    ordering = '-pub_date'

    def get_queryset(self):
        default_sort = self.get_ordering()
        category = self.request.GET.get('category')
        search_string = self.request.GET.get('search_string')
        order_by_date = self.request.GET.get('pub_date')
        order_by_title = self.request.GET.get('title')
        order_by_popularity = self.request.GET.get('popularity')
        sort_order = order_by_date or order_by_title or default_sort

        if category:
            posts = Post.objects\
                .filter(category_id=int(category))\
                .select_related('category')\
                .order_by(sort_order)
        elif search_string:
            posts = Post.objects\
                .filter(Q(title__icontains=search_string) | Q(content__icontains=search_string))\
                .select_related('category')\
                .order_by(sort_order)
        elif order_by_popularity:
            if order_by_popularity == 'asc':
                posts = Post.objects\
                    .annotate(num_profile=Count('profile'))\
                    .select_related('category')\
                    .order_by('-num_profile')
            else:
                posts = Post.objects\
                    .annotate(num_profile=Count('profile'))\
                    .select_related('category')\
                    .order_by('num_profile')
        else:
            posts = Post.objects.select_related('category').order_by(sort_order)
        return posts

    def get_context_data(self, *args, **kwargs):
        order_by_date = self.request.GET.get('pub_date', '-pub_date')
        order_by_title = self.request.GET.get('title', 'title')
        order_by_popularity = self.request.GET.get('popularity', 'desc')
        context = super().get_context_data(*args, **kwargs)
        context['pub_date'] = '-pub_date' if order_by_date == 'pub_date' else 'pub_date'
        context['title'] = 'title' if order_by_title != 'title' else '-title'
        context['popularity'] = 'asc' if order_by_popularity != 'asc' else 'desc'
        return context


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'posts/post_details.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['comment_form'] = CommentForm()
        return context


@login_required
def add_comment(request, post_id):
    if request.method == 'POST':
        post = get_object_or_404(Post, pk=post_id)
        user = request.user
        form = CommentForm(request.POST)

        if post and user:
            if form.is_valid():
                data = form.cleaned_data
                Comment.objects.create(content=data.get('content'), post=post, user=user)

    return redirect(reverse('posts:post_details', kwargs={'pk': post_id}))


@login_required
def remove_comment(request, post_id, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, pk=comment_id)
        user = request.user

        if comment.user == user or user.is_superuser:
            comment.delete()
        else:
            return HttpResponseForbidden()

    return redirect(reverse('posts:post_details', kwargs={'pk': post_id}))

templates/movieblog/posts/index.html
{% extends 'movieblog/base_home.html' %}
{% load static %}

{% block title %}
    Главная страница
{% endblock %}

{% block banner %}
    {% include 'movieblog/posts/filtering.html' %}
    <section class="container banner">
    </section>
{% endblock banner %}

{% block content %}
    {% if posts %}
        <section class="container news">
            <div class="news__wrapper">
                {% for post in posts %}
                    <div class="news__item">
                        {% if post.image %}
                            <img class="news__item-img" src="{{ post.image.url }}" alt="Post image">
                        {% else %}
                            <img class="news__item-img" src="{% static 'images/default_post_img.jpg' %}"
                                 alt="Default post image">
                        {% endif %}
                        {% if user.is_authenticated %}
                            {% if post in user.profile.posts.all %}
                                <form action="{% url 'profiles:bookmark_remove' post.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                    <button class="fav-icon active">
                                        <svg height="511pt" viewBox="0 -10 511.98645 511" width="511pt"
                                             xmlns="http://www.w3.org/2000/svg">
                                            <path d="m499.574219 188.503906c-3.199219-9.921875-11.988281-16.9375-22.398438-17.898437l-141.355469-12.84375-55.894531-130.835938c-4.117187-9.578125-13.503906-15.765625-23.933593-15.765625-10.433594 0-19.820313 6.207032-23.9375 15.808594l-55.890626 130.816406-141.378906 12.839844c-10.386718.941406-19.175781 7.957031-22.378906 17.878906-3.21875 9.921875-.234375 20.777344 7.617188 27.648438l106.859374 93.695312-31.511718 138.773438c-2.300782 10.199218 1.664062 20.734375 10.136718 26.878906 4.519532 3.328125 9.875 4.992188 15.230469 4.992188 4.628907 0 9.238281-1.234376 13.355469-3.710938l121.898438-72.894531 121.875 72.875c8.917968 5.351562 20.160156 4.882812 28.609374-1.238281 8.46875-6.144532 12.4375-16.683594 10.132813-26.882813l-31.507813-138.769531 106.859376-93.699219c7.847656-6.867187 10.835937-17.726563 7.613281-27.667969zm0 0"
                                                  fill="#ffc107"/>
                                            <path d="m114.617188 491.136719c-5.632813 0-11.203126-1.746094-15.957032-5.183594-8.855468-6.398437-12.992187-17.429687-10.582031-28.09375l32.9375-145.066406-111.703125-97.964844c-8.210938-7.1875-11.347656-18.515625-7.976562-28.90625 3.371093-10.367187 12.542968-17.726563 23.402343-18.730469l147.820313-13.417968 58.410156-136.746094c4.308594-10.046875 14.121094-16.535156 25.023438-16.535156 10.902343 0 20.714843 6.488281 25.023437 16.511718l58.410156 136.769532 147.796875 13.417968c10.882813.980469 20.054688 8.34375 23.425782 18.710938 3.371093 10.386718.253906 21.738281-7.980469 28.90625l-111.679688 97.941406 32.9375 145.066406c2.414063 10.667969-1.726562 21.695313-10.578125 28.09375-8.8125 6.378906-20.566406 6.914063-29.890625 1.324219l-127.464843-76.160156-127.445313 76.203125c-4.308594 2.582031-9.109375 3.859375-13.929687 3.859375zm141.375-112.871094c4.84375 0 9.640624 1.300781 13.953124 3.859375l120.277344 71.9375-31.085937-136.941406c-2.21875-9.769532 1.089843-19.925782 8.621093-26.515625l105.472657-92.523438-139.542969-12.671875c-10.003906-.894531-18.667969-7.1875-22.59375-16.46875l-55.101562-129.046875-55.148438 129.066407c-3.902344 9.238281-12.5625 15.53125-22.589844 16.429687l-139.519531 12.671875 105.46875 92.519531c7.554687 6.59375 10.839844 16.769531 8.621094 26.539063l-31.082031 136.941406 120.277343-71.9375c4.328125-2.558594 9.128907-3.859375 13.972657-3.859375zm-84.585938-221.824219v.019532zm169.152344-.066406v.023438s0 0 0-.023438zm0 0"/>
                                        </svg>
                                    </button>
                                </form>
                            {% else %}
                                <form action="{% url 'profiles:bookmark_add' post.id %}"
                                      method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                    <button class="fav-icon">
                                        <svg height="511pt" viewBox="0 -10 511.98685 511" width="511pt"
                                             xmlns="http://www.w3.org/2000/svg">
                                            <path d="m114.59375 491.140625c-5.609375 0-11.179688-1.75-15.933594-5.1875-8.855468-6.417969-12.992187-17.449219-10.582031-28.09375l32.9375-145.089844-111.703125-97.960937c-8.210938-7.167969-11.347656-18.519532-7.976562-28.90625 3.371093-10.367188 12.542968-17.707032 23.402343-18.710938l147.796875-13.417968 58.433594-136.746094c4.308594-10.046875 14.121094-16.535156 25.023438-16.535156 10.902343 0 20.714843 6.488281 25.023437 16.511718l58.433594 136.769532 147.773437 13.417968c10.882813.980469 20.054688 8.34375 23.425782 18.710938 3.371093 10.367187.253906 21.738281-7.957032 28.90625l-111.703125 97.941406 32.9375 145.085938c2.414063 10.667968-1.726562 21.699218-10.578125 28.097656-8.832031 6.398437-20.609375 6.890625-29.910156 1.300781l-127.445312-76.160156-127.445313 76.203125c-4.308594 2.558594-9.109375 3.863281-13.953125 3.863281zm141.398438-112.875c4.84375 0 9.640624 1.300781 13.953124 3.859375l120.277344 71.9375-31.085937-136.941406c-2.21875-9.746094 1.089843-19.921875 8.621093-26.515625l105.472657-92.5-139.542969-12.671875c-10.046875-.917969-18.6875-7.234375-22.613281-16.492188l-55.082031-129.046875-55.148438 129.066407c-3.882812 9.195312-12.523438 15.511718-22.546875 16.429687l-139.5625 12.671875 105.46875 92.5c7.554687 6.613281 10.859375 16.769531 8.621094 26.539062l-31.0625 136.9375 120.277343-71.914062c4.308594-2.558594 9.109376-3.859375 13.953126-3.859375zm-84.585938-221.847656s0 .023437-.023438.042969zm169.128906-.0625.023438.042969c0-.023438 0-.023438-.023438-.042969zm0 0"/>
                                        </svg>
                                    </button>
                                </form>
                            {% endif %}
                        {% endif %}

                        <a href="{% url 'posts:post_details' post.id %}" class="news__item-details">Подробнее</a>
                        <div class="news__item-header">
                            <span class="news__item-category">{{ post.category.name }}</span>
                            <p class="news__item-title">{{ post.title|truncatechars:80 }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if posts|length_is:6 %}
                <a href="{% url 'posts:post_list' %}" class="news__all">Показать все новости</a>
            {% endif %}
        </section>
    {% endif %}
{% endblock content %}

templates/movieblog/posts/post_details.html
{% extends 'movieblog/base_home.html' %}
{% load humanize %}
{% load static %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block navbar %}
    {% include 'movieblog/navbar.html' with categories=categories %}
{% endblock navbar %}

{% block content %}
    {% if post.image %}
        <section class="container banner"
                 style="background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url({{ post.image.url }}) no-repeat center top / cover">
    {% else %}
        <section class="container banner"
                 style="background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url({% static 'images/default_post_img.jpg' %}) no-repeat center top / cover">
    {% endif %}
<div class="banner__content">
    <h1 class="banner__content-title">{{ post.title }}</h1>
    <span class="banner__content-category">{{ post.category.name }}</span>
    <span class="banner__content-date">{{ post.pub_date }}</span>
</div>
</section>
<section class="container post">
    <div class="post__content">
        {{ post.content|safe }}
    </div>
    <hr>
    <div class="post__comments">
        <h1>Комментарии</h1>
        {% for comment in post.comment_set.all %}
            <div class="post__comments-wrapper">
                {% if comment.user.profile.image %}
                    <img class="post__comments-user-icon" src="{{ comment.user.profile.image.url }}"
                         alt="User image">
                {% else %}
                    <img class="post__comments-user-icon" src="{% static 'images/default_user_img.png' %}"
                         alt="User image">
                {% endif %}
                <div class="post__comments-content">
                    <div class="post__comments-details">
                        <span class="post__comments-username">{{ comment.user.username }}</span>
                        {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                                <form action="{% url 'posts:comment_remove' post_id=post.id comment_id=comment.id %}"
                                      method="post" class="post__comments-delete">
                                    {% csrf_token %}
                                    <button type="submit">
                                        <svg xmlns:xlink="http://www.w3.org/1999/xlink"
                                             viewBox="0 0 512.001 512.001" xml:space="preserve">
                                            <g>
                                                <g>
                                                    <path d="M294.111,256.001L504.109,46.003c10.523-10.524,10.523-27.586,0-38.109c-10.524-10.524-27.587-10.524-38.11,0L256,217.892
                                                                                    L46.002,7.894c-10.524-10.524-27.586-10.524-38.109,0s-10.524,27.586,0,38.109l209.998,209.998L7.893,465.999
                                                                                    c-10.524,10.524-10.524,27.586,0,38.109c10.524,10.524,27.586,10.523,38.109,0L256,294.11l209.997,209.998
                                                                                    c10.524,10.524,27.587,10.523,38.11,0c10.523-10.524,10.523-27.586,0-38.109L294.111,256.001z"/>
                                                </g>
                                            </g>
                                        </svg>
                                    </button>
                                </form>
                            {% elif comment.user.username == user.username %}
                                <form action="{% url 'posts:comment_remove' post_id=post.id comment_id=comment.id %}"
                                      class="post__comments-delete">
                                    <button type="submit">
                                        <svg xmlns:xlink="http://www.w3.org/1999/xlink"
                                             viewBox="0 0 512.001 512.001" xml:space="preserve">
                                            <g>
                                                <g>
                                                    <path d="M294.111,256.001L504.109,46.003c10.523-10.524,10.523-27.586,0-38.109c-10.524-10.524-27.587-10.524-38.11,0L256,217.892
                                                                                                                            L46.002,7.894c-10.524-10.524-27.586-10.524-38.109,0s-10.524,27.586,0,38.109l209.998,209.998L7.893,465.999
                                                                                                                            c-10.524,10.524-10.524,27.586,0,38.109c10.524,10.524,27.586,10.523,38.109,0L256,294.11l209.997,209.998
                                                                                                                            c10.524,10.524,27.587,10.523,38.11,0c10.523-10.524,10.523-27.586,0-38.109L294.111,256.001z"/>
                                                </g>
                                            </g>
                                        </svg>
                                    </button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>
                    <p>
                        {{ comment.content }}
                    </p>
                    <span class="post__comments-date">{{ comment.pub_date|naturaltime }}</span>
                </div>
            </div>
        {% endfor %}

        {% if user.is_authenticated %}
            <form action="{% url 'posts:comment_add' post.id %}" class="post__comments-form" method="post">
                {% csrf_token %}
                {% if user.profile.image %}
                    <img class="post__comments-user-icon" src="{{ user.profile.image.url }}" alt="User image">
                {% else %}
                    <img class="post__comments-user-icon" src="{% static 'images/default_user_img.png' %}"
                         alt="User image">
                {% endif %}
                {{ comment_form.content }}
                <button type="submit">
                    <svg height="512" viewBox="0 0 465.882 465.882" width="512" xmlns="http://www.w3.org/2000/svg">
                        <path d="m465.882 0-465.882 262.059 148.887 55.143 229.643-215.29-174.674 235.65.142.053-.174-.053v128.321l83.495-97.41 105.77 39.175z"/>
                    </svg>
                </button>
            </form>
        {% endif %}

    </div>
    <aside class="social-media">
        <div class="social-media-wrapper">
            <a href="https://vk.com/share.php?url=@enc&title=@text" target="_blank">
                <img src="{% static 'images/017-vk.png' %}" alt="vk share icon">
            </a>
            <a href="https://twitter.com/intent/tweet?url=@enc&text=@text" target="_blank">
                <img src="{% static 'images/001-twitter.png' %}" alt="twitter share icon">
            </a>
            <a href="https://www.facebook.com/sharer/sharer.php?u=@enc" target="_blank">
                <img src="{% static 'images/008-facebook.png' %}" alt="facebook share icon">
            </a>
        </div>
    </aside>
</section>
{% endblock content %}

templates/movieblog/posts/post_list.html
{% extends 'movieblog/base_home.html' %}
{% load static %}

{% block title %}
    Новости
{% endblock %}

{% block content %}
    {% include 'movieblog/posts/filtering.html' %}

    <section class="container news">
        {% if posts %}
            <div class="news__wrapper">
                {% for post in posts %}
                    <div class="news__item">
                        {% if post.image %}
                            <img class="news__item-img" src="{{ post.image.url }}" alt="Post image">
                        {% else %}
                            <img class="news__item-img" src="{% static 'images/default_post_img.jpg' %}"
                                 alt="Default post image">
                        {% endif %}
                        {% if user.is_authenticated %}
                            {% if post in user.profile.posts.all %}
                                <form action="{% url 'profiles:bookmark_remove' post.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                    <button class="fav-icon active">
                                        <svg height="511pt" viewBox="0 -10 511.98645 511" width="511pt"
                                             xmlns="http://www.w3.org/2000/svg">
                                            <path d="m499.574219 188.503906c-3.199219-9.921875-11.988281-16.9375-22.398438-17.898437l-141.355469-12.84375-55.894531-130.835938c-4.117187-9.578125-13.503906-15.765625-23.933593-15.765625-10.433594 0-19.820313 6.207032-23.9375 15.808594l-55.890626 130.816406-141.378906 12.839844c-10.386718.941406-19.175781 7.957031-22.378906 17.878906-3.21875 9.921875-.234375 20.777344 7.617188 27.648438l106.859374 93.695312-31.511718 138.773438c-2.300782 10.199218 1.664062 20.734375 10.136718 26.878906 4.519532 3.328125 9.875 4.992188 15.230469 4.992188 4.628907 0 9.238281-1.234376 13.355469-3.710938l121.898438-72.894531 121.875 72.875c8.917968 5.351562 20.160156 4.882812 28.609374-1.238281 8.46875-6.144532 12.4375-16.683594 10.132813-26.882813l-31.507813-138.769531 106.859376-93.699219c7.847656-6.867187 10.835937-17.726563 7.613281-27.667969zm0 0"
                                                  fill="#ffc107"/>
                                            <path d="m114.617188 491.136719c-5.632813 0-11.203126-1.746094-15.957032-5.183594-8.855468-6.398437-12.992187-17.429687-10.582031-28.09375l32.9375-145.066406-111.703125-97.964844c-8.210938-7.1875-11.347656-18.515625-7.976562-28.90625 3.371093-10.367187 12.542968-17.726563 23.402343-18.730469l147.820313-13.417968 58.410156-136.746094c4.308594-10.046875 14.121094-16.535156 25.023438-16.535156 10.902343 0 20.714843 6.488281 25.023437 16.511718l58.410156 136.769532 147.796875 13.417968c10.882813.980469 20.054688 8.34375 23.425782 18.710938 3.371093 10.386718.253906 21.738281-7.980469 28.90625l-111.679688 97.941406 32.9375 145.066406c2.414063 10.667969-1.726562 21.695313-10.578125 28.09375-8.8125 6.378906-20.566406 6.914063-29.890625 1.324219l-127.464843-76.160156-127.445313 76.203125c-4.308594 2.582031-9.109375 3.859375-13.929687 3.859375zm141.375-112.871094c4.84375 0 9.640624 1.300781 13.953124 3.859375l120.277344 71.9375-31.085937-136.941406c-2.21875-9.769532 1.089843-19.925782 8.621093-26.515625l105.472657-92.523438-139.542969-12.671875c-10.003906-.894531-18.667969-7.1875-22.59375-16.46875l-55.101562-129.046875-55.148438 129.066407c-3.902344 9.238281-12.5625 15.53125-22.589844 16.429687l-139.519531 12.671875 105.46875 92.519531c7.554687 6.59375 10.839844 16.769531 8.621094 26.539063l-31.082031 136.941406 120.277343-71.9375c4.328125-2.558594 9.128907-3.859375 13.972657-3.859375zm-84.585938-221.824219v.019532zm169.152344-.066406v.023438s0 0 0-.023438zm0 0"/>
                                        </svg>
                                    </button>
                                </form>
                            {% else %}
                                <form action="{% url 'profiles:bookmark_add' post.id %}"
                                      method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.get_full_path }}">
                                    <button class="fav-icon">
                                        <svg height="511pt" viewBox="0 -10 511.98685 511" width="511pt"
                                             xmlns="http://www.w3.org/2000/svg">
                                            <path d="m114.59375 491.140625c-5.609375 0-11.179688-1.75-15.933594-5.1875-8.855468-6.417969-12.992187-17.449219-10.582031-28.09375l32.9375-145.089844-111.703125-97.960937c-8.210938-7.167969-11.347656-18.519532-7.976562-28.90625 3.371093-10.367188 12.542968-17.707032 23.402343-18.710938l147.796875-13.417968 58.433594-136.746094c4.308594-10.046875 14.121094-16.535156 25.023438-16.535156 10.902343 0 20.714843 6.488281 25.023437 16.511718l58.433594 136.769532 147.773437 13.417968c10.882813.980469 20.054688 8.34375 23.425782 18.710938 3.371093 10.367187.253906 21.738281-7.957032 28.90625l-111.703125 97.941406 32.9375 145.085938c2.414063 10.667968-1.726562 21.699218-10.578125 28.097656-8.832031 6.398437-20.609375 6.890625-29.910156 1.300781l-127.445312-76.160156-127.445313 76.203125c-4.308594 2.558594-9.109375 3.863281-13.953125 3.863281zm141.398438-112.875c4.84375 0 9.640624 1.300781 13.953124 3.859375l120.277344 71.9375-31.085937-136.941406c-2.21875-9.746094 1.089843-19.921875 8.621093-26.515625l105.472657-92.5-139.542969-12.671875c-10.046875-.917969-18.6875-7.234375-22.613281-16.492188l-55.082031-129.046875-55.148438 129.066407c-3.882812 9.195312-12.523438 15.511718-22.546875 16.429687l-139.5625 12.671875 105.46875 92.5c7.554687 6.613281 10.859375 16.769531 8.621094 26.539062l-31.0625 136.9375 120.277343-71.914062c4.308594-2.558594 9.109376-3.859375 13.953126-3.859375zm-84.585938-221.847656s0 .023437-.023438.042969zm169.128906-.0625.023438.042969c0-.023438 0-.023438-.023438-.042969zm0 0"/>
                                        </svg>
                                    </button>
                                </form>
                            {% endif %}
                        {% endif %}

                        <a href="{% url 'posts:post_details' post.id %}" class="news__item-details">Подробнее</a>
                        <div class="news__item-header">
                            <span class="news__item-category">{{ post.category.name }}</span>
                            <p class="news__item-title">{{ post.title|truncatechars:80 }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {% if is_paginated %}
                <div class="post__pagination-container">
                    <ul class="post__pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">Назад</a></li>
                        {% else %}
                            <li><span class="disabled">Назад</span></li>
                        {% endif %}
                        {% for page_number in paginator.page_range %}
                            {% if page_number == page_obj.number %}
                                <li class="page active"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                            {% elif page_number > page_obj.number|add:'-4' and page_number < page_obj.number|add:'4' %}
                                <li class="page"><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">Вперёд</a></li>
                        {% else %}
                            <li><span class="disabled">Вперёд</span></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}

        {% else %}
            <div class="news__not-found">
                <img src="{% static 'images/036-film-reel.png' %}" alt="frame icon">
                <h1>Ничего не найдено</h1>
            </div>
        {% endif %}
    </section>

{% endblock content %}